---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - gistic_cloudera::oracle_java
      - gistic_cloudera::init_single_user_mode
      - gistic_cloudera::install_cdh5
    attributes:
